name: xcube
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python =3.7
  # Required
  - affine =2.2
  - blas =*=mkl
  - click =7.0
  - cmocean =2.0
  - dask =1.2
  - fiona =1.8
  - gdal =2.4
  - matplotlib =3.0
  - netcdf4 =1.5.0
  - numba =0.43
  - numpy =1.16
  - pandas =0.24
  - pillow =6.0
  - proj4 =5.2
  - pyyaml =5.1
  - rasterio =1.0
  - s3fs =0.2
  - scipy =1.2
  - setuptools =41.0
  - shapely =1.6
  - tornado =6.0
  - xarray =0.12
  - zarr =2.3
  - sphinx =2.0.1
  # Testing
  - flake8 =3.7
  - pytest =4.4
  - pytest-cov =2.6

